"""[ADDITION] case advocates model added

Revision ID: a4a6c0e6a102
Revises: d73a2781fbe8
Create Date: 2025-03-29 18:41:32.871487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4a6c0e6a102'
down_revision: Union[str, None] = 'd73a2781fbe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advocate_details',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(length=14), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('bar_council_number', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bar_council_number'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_advocate_details_id'), 'advocate_details', ['id'], unique=False)
    op.create_table('case_advocates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('advocate_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['advocate_id'], ['advocate_details.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_advocates_id'), 'case_advocates', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_advocates_id'), table_name='case_advocates')
    op.drop_table('case_advocates')
    op.drop_index(op.f('ix_advocate_details_id'), table_name='advocate_details')
    op.drop_table('advocate_details')
    # ### end Alembic commands ###
