"""[Initial Migrtation] creating tables

Revision ID: d73a2781fbe8
Revises: 
Create Date: 2025-03-29 18:16:48.372433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd73a2781fbe8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.Column('case_title', sa.String(), nullable=False),
    sa.Column('court_name', sa.String(), nullable=False),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('upcoming_hearing_date', sa.Date(), nullable=True),
    sa.Column('case_status', sa.Enum('OPEN', 'CLOSED', 'PENDING', name='casestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_number')
    )
    op.create_index(op.f('ix_cases_id'), 'cases', ['id'], unique=False)
    op.create_table('case_hearing',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('hearing_date', sa.Date(), nullable=True),
    sa.Column('judge_name', sa.String(), nullable=True),
    sa.Column('rival_advocate_name', sa.String(), nullable=True),
    sa.Column('hearing_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('order_details', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_orders')
    op.drop_table('case_hearing')
    op.drop_index(op.f('ix_cases_id'), table_name='cases')
    op.drop_table('cases')
    # ### end Alembic commands ###
